source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZenCopy_Example', :exclusive => true do
  pod 'ZenCopy', :path => '../'
end

target 'ZenCopy_Tests', :exclusive => true do
  pod 'ZenCopy', :path => '../'

  pod 'Quick'
  pod 'Nimble'
end
